name: Code Style Check

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  astyle-check:
    runs-on: ubuntu-latest
    steps:
      - name: Style
        working-directory: ZSWatch
        run: |
          west format --dry-run
